# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8d12f521e0b17f7240d12808985f593654c1b6aadd9d5d4eade2b16c4a586d7763f89184bd065ed1926fe32d28490f64b7657f23b2ecc7b8b09f125929d9c1f

test:
  secret_key_base: 72e552b344d7623d25e687ad60f5fd2693a67cf0b25048671bd75937428a6082785a1210c8501732787d507500c309ba2fc24c261377e4c36c8c22ae155ff0c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
